### ISSUE TITLE
Does not work on Nexus 5

### ISSUE THREAD

**Issue by Joeoc2001** [nfcgate/sniffer#1]
When running this app on a rooted Nexus 5 I found that the function `com.android.nfc.NfcService.TagService::transceive` was inaccessible, preventing Xposed from hooking onto it.

**Comment by roussosalex** [comment]
Thank you for your contribution, but this repository is deprecated in favor of [on-device capture mode](/nfcgate/nfcgate/blob/v2/doc/mode/OnDevice.md) in NfcGate.
